name: Deploy Bicep Template

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
      RESOURCE_GROUP: aguadamillas_students_1
      SUBSCRIPTION_ID: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
      USER_ALIAS: LeoMuci

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy Bicep template
      run: |
        az deployment group create \
          --resource-group aguadamillas_students_1 \
          --template-file ./main.bicep \
          --parameters @dev.parameters.json \
          --parameters DOCKER_REGISTRY_SERVER_URL=${{ secrets.DOCKER_REGISTRY_SERVER_URL }} \
          --parameters DOCKER_REGISTRY_SERVER_USERNAME=${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }} \
          --parameters DOCKER_REGISTRY_SERVER_PASSWORD=${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }} \